class AddStemsToPabs < ActiveRecord::Migration
    def up
        
    end
    
    def down
      remove_column :responses, :stem1_question_a
      remove_column :responses, :stem1_question_b
      remove_column :responses, :stem1_question_c
      remove_column :responses, :stem1_question_d
      remove_column :responses, :stem1_question_e
      remove_column :responses, :stem1_question_f
      remove_column :responses, :stem1_question_g
      remove_column :responses, :stem1_question_h
      remove_column :responses, :stem2_question_a
      remove_column :responses, :stem2_question_b
      remove_column :responses, :stem2_question_c
      remove_column :responses, :stem2_question_d
      remove_column :responses, :stem2_question_e
      remove_column :responses, :stem2_question_f
      remove_column :responses, :stem2_question_g
      remove_column :responses, :stem2_question_h
      remove_column :responses, :stem3_question_a
      remove_column :responses, :stem3_question_b
      remove_column :responses, :stem3_question_c
      remove_column :responses, :stem3_question_d
      remove_column :responses, :stem3_question_e
      remove_column :responses, :stem3_question_f
      remove_column :responses, :stem3_question_g
      remove_column :responses, :stem3_question_h
      remove_column :responses, :stem4_question_a
      remove_column :responses, :stem4_question_b
      remove_column :responses, :stem4_question_c
      remove_column :responses, :stem4_question_d
      remove_column :responses, :stem4_question_e
      remove_column :responses, :stem4_question_f
      remove_column :responses, :stem4_question_g
      remove_column :responses, :stem4_question_h
      remove_column :responses, :stem5_question_a
      remove_column :responses, :stem5_question_b
      remove_column :responses, :stem5_question_c
      remove_column :responses, :stem5_question_d
      remove_column :responses, :stem5_question_e
      remove_column :responses, :stem5_question_f
      remove_column :responses, :stem5_question_g
      remove_column :responses, :stem5_question_h
      remove_column :responses, :stem6_question_a
      remove_column :responses, :stem6_question_b
      remove_column :responses, :stem6_question_c
      remove_column :responses, :stem6_question_d
      remove_column :responses, :stem6_question_e
      remove_column :responses, :stem6_question_f
      remove_column :responses, :stem6_question_g
      remove_column :responses, :stem6_question_h
      remove_column :responses, :stem7_question_a
      remove_column :responses, :stem7_question_b
      remove_column :responses, :stem7_question_c
      remove_column :responses, :stem7_question_d
      remove_column :responses, :stem7_question_e
      remove_column :responses, :stem7_question_f
      remove_column :responses, :stem7_question_g
      remove_column :responses, :stem7_question_h
      remove_column :responses, :stem8_question_a
      remove_column :responses, :stem8_question_b
      remove_column :responses, :stem8_question_c
      remove_column :responses, :stem8_question_d
      remove_column :responses, :stem8_question_e
      remove_column :responses, :stem8_question_f
      remove_column :responses, :stem8_question_g
      remove_column :responses, :stem8_question_h
      remove_column :responses, :stem9_question_a
      remove_column :responses, :stem9_question_b
      remove_column :responses, :stem9_question_c
      remove_column :responses, :stem9_question_d
      remove_column :responses, :stem9_question_e
      remove_column :responses, :stem9_question_f
      remove_column :responses, :stem9_question_g
      remove_column :responses, :stem9_question_h
      remove_column :responses, :stem10_question_a
      remove_column :responses, :stem10_question_b
      remove_column :responses, :stem10_question_c
      remove_column :responses, :stem10_question_d
      remove_column :responses, :stem10_question_e
      remove_column :responses, :stem10_question_f
      remove_column :responses, :stem10_question_g
      remove_column :responses, :stem10_question_h
      remove_column :responses, :stem11_question_a
      remove_column :responses, :stem11_question_b
      remove_column :responses, :stem11_question_c
      remove_column :responses, :stem11_question_d
      remove_column :responses, :stem11_question_e
      remove_column :responses, :stem11_question_f
      remove_column :responses, :stem11_question_g
      remove_column :responses, :stem11_question_h
      remove_column :responses, :stem12_question_a
      remove_column :responses, :stem12_question_b
      remove_column :responses, :stem12_question_c
      remove_column :responses, :stem12_question_d
      remove_column :responses, :stem12_question_e
      remove_column :responses, :stem12_question_f
      remove_column :responses, :stem12_question_g
      remove_column :responses, :stem12_question_h
      remove_column :responses, :stem13_question_a
      remove_column :responses, :stem13_question_b
      remove_column :responses, :stem13_question_c
      remove_column :responses, :stem13_question_d
      remove_column :responses, :stem13_question_e
      remove_column :responses, :stem13_question_f
      remove_column :responses, :stem13_question_g
      remove_column :responses, :stem13_question_h
      remove_column :responses, :stem14_question_a
      remove_column :responses, :stem14_question_b
      remove_column :responses, :stem14_question_c
      remove_column :responses, :stem14_question_d
      remove_column :responses, :stem14_question_e
      remove_column :responses, :stem14_question_f
      remove_column :responses, :stem14_question_g
      remove_column :responses, :stem14_question_h
      remove_column :responses, :stem15_question_a
      remove_column :responses, :stem15_question_b
      remove_column :responses, :stem15_question_c
      remove_column :responses, :stem15_question_d
      remove_column :responses, :stem15_question_e
      remove_column :responses, :stem15_question_f
      remove_column :responses, :stem15_question_g
      remove_column :responses, :stem15_question_h
      remove_column :responses, :stem16_question_a
      remove_column :responses, :stem16_question_b
      remove_column :responses, :stem16_question_c
      remove_column :responses, :stem16_question_d
      remove_column :responses, :stem16_question_e
      remove_column :responses, :stem16_question_f
      remove_column :responses, :stem16_question_g
      remove_column :responses, :stem16_question_h
    end
end
